version 1.4 notes & docs
HorizenOfficial/eon pull request #107
Opened 2024-05-07 09:03 UTC by paolocappelletti

## Description
Prepare 1.4 final on-project documentation:

- changelog
- release notes
- yaml file update
- native smart contracts and api endpoints documentation on git

## Jira Ticket
[SDK-1803](https://horizenlabs.atlassian.net/browse/SDK-1803)

2024-05-10 11:08 UTC, saratnt requested changes

2024-05-10 11:08 UTC, saratnt commented on CHANGELOG.md
> +* Fork configuration to enable new on-chain delegated staking reward mechanism
Should be mentioned the change of the rewards from mainchain too? It is described in SDK changelog but so are the new staking and the metrics endpoint but they are explicitly mentioned here.

2024-05-10 11:08 UTC, saratnt commented on doc/api/index.md
> +[/transaction/updateForger](/doc/api/transaction/updateForger.md)\
The last \ should be removed

2024-05-10 11:08 UTC, saratnt commented on doc/api/index.md
>  #### Forge stakes management:
Shouldn't be mentioned here also metrics API?

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/pagedForgersStakesByDelegator.md
> +| size     | integer | no (dafault 10)| Number of records to return |
typo: dafault => default

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/pagedForgersStakesByDelegator.md
> +| nonce    | integer | no        | Nonce associated to the address that is sending the tx. If omitted the next valid nonce will be calculated automatically.  |
Actually, it is not really true, it is taken the last nonce in the stateDb. This means that if one uses this method twice before a block containing the first transaction is applied to the state, both txs will have the same nonce and only the one with highest gasPrice will remain in the mempool. 
Maybe it can be said "If omitted, the latest nonce saved in the state will be used by default."
Same for all the APIs.

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/pagedForgersStakesByDelegator.md
> +| gasInfo  | object  | no        | Info about GAS |
Gas could be lower case

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/pagedForgersStakesByDelegator.md
> +Returns the paginated list of forging stakes, filtered by a specific delegator.<br>
Maybe also return parameters should be described

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/pagedForgersStakesByForger.md
> +### transaction/pagedForgerStakesByForger
Same comments as pagedForgerSTakesByDelegator

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/registerForger.md
> +| vrfPubKey | string |yes | Vrfkey of this forger(private key must be in the local wallet) |
Missing a space between forger(private

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/updateForger.md
> +Update an exisitng forger.<br>
typo: exisitng => existing

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/updateForger.md
> +| vrfPubKey | string |yes | Vrfkey of this forger(private key must be in the local wallet) |
A space is missing in forger(private

2024-05-10 11:08 UTC, saratnt commented on doc/api/transaction/updateForger.md
> +        "stakedAmount": "100000000000",
stakedAmount is not needed for updateForger

2024-05-10 11:08 UTC, saratnt commented on doc/nativesc/contracts/ForgerStakesV2.sol
> +pragma solidity ^0.8.0;
This misses the stakeStart method. Same the json

2024-05-10 11:08 UTC, saratnt commented on doc/nativesc/contracts/ForgerStakesV2.md
> +     Each element of the list is the total amount delegated by a specific address. The datasctucture has the following format:<br>
typo: datasctucture => data structure
Same elsewhere in this file

2024-05-10 11:08 UTC, saratnt commented on doc/nativesc/contracts/ForgerStakesV2.md
> +     Withdraw (unstake) a previously assigned stake.<br>
Maybe it can be added that the amount is added to the balance of the sender of the transaction.

2024-05-10 11:08 UTC, saratnt commented on doc/nativesc/contracts/ForgerStakesV2.md
> +     be < maxNumOfEpoch if the current consensus epoch is < (consensusEpochStart + maxNumOfEpoch) or if the forger was
It should be actually current consensus epoch is < (consensusEpochStart + maxNumOfEpoch - 1)
In addition, in case the forger was registered after consensusEpochStart, the array length doesn't change, the epochs where the forger wasn't registered have 0 value so the first element always corresponds to consensusEpochStart

2024-05-10 11:08 UTC, saratnt commented on doc/nativesc/contracts/ForgerStakesV2.md
> +     vrf, signKey and delegator are optional: if all are null, the total stake amount will be returned. If only
Maybe it is better to specify what we actually mean with null in this context.
For bytes parameters, as addresses of key etc.), a byte array of the expected length with all 0 values is interpreted as null, eg "0x0000000000000000000000000000000000000000" for addresses). For consensusEpochStart and maxNumOfEpoch, it is 0.
Also the Solidity interface should be updated as well

2024-05-10 11:08 UTC, saratnt commented on doc/nativesc/contracts/ForgerStakesV2.md
> +          function rewardsReceived(bytes32 signPubKey, bytes32 vrf1, bytes1 vrf2, uint32 consensusEpochStart, uint32 maxNumOfEpoch) external view returns (uint256[] memory listOfRewards);
same as stakeTotal with the only difference that the rewards corresponding to the current epoch are never returned

2024-05-10 11:08 UTC, saratnt commented on doc/nativesc/contracts/ForgerStakesV2.md
> +     Activation function for this smart contract. Must be called only onetime after the hardfork. After the activation the old ForgerStake native smart contract will be de-activated.
typo: onetime => once

2024-05-10 11:08 UTC, saratnt commented on doc/nativesc/contracts/ForgerStakesV2.md
> +
It is missing stakeStart method description

2024-05-13 07:27 UTC, paolocappelletti commented on CHANGELOG.md
> +* Fork configuration to enable new on-chain delegated staking reward mechanism
added in the fork section

2024-05-13 07:34 UTC, paolocappelletti commented on doc/api/transaction/pagedForgersStakesByDelegator.md
> +| gasInfo  | object  | no        | Info about GAS |
is already upper case in other endpoints, will keep it

2024-05-13 07:42 UTC, paolocappelletti commented on doc/api/transaction/pagedForgersStakesByDelegator.md
> +Returns the paginated list of forging stakes, filtered by a specific delegator.<br>
they are quite self explaining, will keep as is for now :-)

2024-05-13 13:39 UTC, saratnt approved these changes

2024-05-14 06:46 UTC, merged