Fix for issue EON-1857
HorizenOfficial/eon pull request #110
Opened 2024-05-28 16:08 UTC by alsala

Fix for issue [EON-1857](https://horizenlabs.atlassian.net/browse/EON-1857)

The fix consists in preventing the `updateForger` operation for the 2 epochs after the 1.4 fork activation, assuming that the V2 activation happens in the same epoch.

This fix has a companion fix in Sidechain-Sdk repository

2024-05-29 07:41 UTC, saratnt requested changes
Some doc files should be updated too for explaining that updateForger cannot be called before 2 epochs after activation:

- doc/nativesc/contracts/ForgerStakesV2.sol
- doc/api/transaction/updateForger.md
- doc/nativesc/contracts/ForgerStakesV2.md

2024-05-29 15:48 UTC, alsala commented
> Some doc files should be updated too for explaining that updateForger cannot be called before 2 epochs after activation:
> 
>     * doc/nativesc/contracts/ForgerStakesV2.sol
> 
>     * doc/api/transaction/updateForger.md
> 
>     * doc/nativesc/contracts/ForgerStakesV2.md

Done

2024-05-29 15:52 UTC, saratnt approved these changes

2024-05-30 10:26 UTC, paolocappelletti approved these changes

2024-05-30 10:27 UTC, merged