EON version binding
HorizenOfficial/eon pull request #28
Opened 2023-06-16 13:29 UTC by ddrvar

[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-1207?atlOrigin=eyJpIjoiYWExMDcyNjY4ZGI0NDNlODg1ZWY4ZDFkOGY1ZGI5NzQiLCJwIjoiaiJ9)

EON version is taken from the class package implementation version which is specified in pom.xml file. When running EON from IDE, it returns `null` because the implementation version is populated when JAR is built. It follows the logic of sdk version taken from [here](https://github.com/HorizenOfficial/Sidechains-SDK/blob/7729cae9fd10670e57f02decc418b552906eab0c/sdk/src/main/scala/io/horizen/account/api/rpc/service/RpcUtils.scala#LL16C1-L17C1).

2023-06-19 12:20 UTC, MarcoOl94 requested changes

2023-06-19 12:20 UTC, MarcoOl94 commented on node/src/main/java/io/horizen/eon/EonAppModule.java
> +                .annotatedWith(Names.named("EonVersion"))
Eon -> App

2023-06-19 12:20 UTC, MarcoOl94 commented on node/src/main/java/io/horizen/eon/EonAppModule.java
> +        String defaultVersion = "dev";
To me it should be better to enforce having a declared version. I would like to always read the version from the pom, but please sync up with @paolocappelletti if this is an acceptable behavior.

2023-06-20 09:03 UTC, ddrvar commented on node/src/main/java/io/horizen/eon/EonAppModule.java
> +                .annotatedWith(Names.named("EonVersion"))
Done

2023-06-20 09:50 UTC, ddrvar commented on node/src/main/java/io/horizen/eon/EonAppModule.java
> +        String defaultVersion = "dev";
Retrieves the EON version by dynamically accessing the implementation version of the package at runtime.
The implementation version is taken from the JAR file's manifest file **Implementation-Version** attribute. That attribute
is populated when JAR is built with the value of the version tag under the project key from the pom file. 
When running the application in a development environment (e.g., directly from the source code or an IDE), the implementation version is not accessible and will return the default "dev" value.

2023-06-20 14:17 UTC, MarcoOl94 approved these changes

2023-06-27 13:19 UTC, paolocappelletti approved these changes

2023-06-27 13:20 UTC, merged